name: cbl_flutter_platform_interface
description: Platform interface for the Couchbase Lite Flutter plugin.
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl
      ref: test
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
