name: cbl_e2e_tests_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  benchmark_harness: ^2.1.0
  cbl:
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl
      ref: GA
  cbl_e2e_tests:
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_e2e_tests
      ref: GA
  cbl_flutter: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter
      ref: GA
  cbl_flutter_local:
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter_local
      ref: GA
  collection: ^1.16.0
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^1.0.0
  integration_test:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.1
  path_provider: ^2.0.10
  rxdart: ^0.27.3
  stream_channel: ^2.1.0
  test: ^1.21.1
  web_socket_channel: ^2.2.0

flutter:
  assets:
    - packages/cbl_e2e_tests/src/fixtures/1000people.json
