name: cbl_performance_logger
publish_to: none
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.0.0

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
