name: cbl_flutter
publish_to: none
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.0.0

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl
      ref: test
  cbl_flutter_platform_interface: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter_platform_interface
      ref: test
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
