name: cbl_flutter_multiplatform
publish_to: none
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.0.0

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  http: ^1.2.0
  cbl: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl
      ref: GA
  cbl_flutter: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter
      ref: GA
  cbl_flutter_ee: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter_ee
      ref: GA
  cbl_flutter_web: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_flutter_web
      ref: GA
  cbl_web: 
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_web
      ref: GA
  cbl_performance_logger:
    git:
      url: https://github.com/couchbaselabs/mobile-dart-flutter-plugin.git
      path: packages/cbl_performance_logger
      ref: GA
  flutter:
    sdk: flutter
