name: cbl_flutter_multiplatform
publish_to: none
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.0.0

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: 
    path: '../cbl'
  cbl_flutter: 
    path: '../cbl_flutter'
  cbl_flutter_ee: 
    path: '../cbl_flutter_ee'
  cbl_flutter_web: 
    path: '../cbl_flutter_web'
  cbl_web: 
    path: '../cbl_web'
  flutter:
    sdk: flutter
